[game]
hostname         = "[EN][MRP] Delta-v (Î¨) | Apoapsis [US East 1]"
<<<<<<< HEAD
soft_max_players = 80
<<<<<<< HEAD
auto_unlock_aa_enabled = false # Disabled for apo until if/when command whitelist
=======
>>>>>>> 496c0c511e446e3b6ce133b750e6003484d66e30
=======
soft_max_players = 100
>>>>>>> 9f6826ca6b052f8cef3a47cb9281a73b2877903d

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"

[debug]
pow3r_disable_parallel = false
